[WIP]掲示板の詳細表示機能を追加
junkratmecha/tenkue-board-r002 pull request #1
Opened 2020-09-15 16:51 UTC by helloTsubasa

[概要]
Trello #掲示板詳細表示機能
掲示板の詳細表示機能を追加する

[変更点]
あとで記載します

2020-09-23 08:44 UTC, sew-sou19 requested changes
レビュー完了しましたー！
修正後再度依頼してください！

2020-09-23 08:44 UTC, sew-sou19 commented on app/assets/javascripts/posts.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
不要なファイルは削除しましょうー！
今回はcoffeeファイルは使用しないかと思うので！

2020-09-23 08:44 UTC, sew-sou19 commented on app/assets/stylesheets/posts.scss
> +// Place all the styles related to the posts controller here.
こちらも使用しないなら削除しましょう！

2020-09-23 08:44 UTC, sew-sou19 commented on app/views/posts/show.html.erb
> +            <span>投稿日時：<%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></span>
日時の表示形式指定は、ヘルパーメソッドにまとめてあげると便利&DRY原則に沿った記述にできます！
app/views/posts/index.html.erbでも同様の記述があるので、そこもまとめて変えてあげるといいです

2020-09-23 08:44 UTC, sew-sou19 commented on config/routes.rb
> +  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show]
7つのアクションすべて指定しているので、下記が良いと思います！
```suggestion
  resources :posts
```

2020-09-23 16:53 UTC, helloTsubasa commented on app/assets/javascripts/posts.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
削除しました！

2020-09-23 16:54 UTC, helloTsubasa commented on app/assets/stylesheets/posts.scss
> +// Place all the styles related to the posts controller here.
こちらも削除しました！

2020-09-23 17:10 UTC, helloTsubasa commented on app/views/posts/show.html.erb
> +            <span>投稿日時：<%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></span>
ヘルパーメソッドにまとめ、DRY原則に沿った記述に変更しました！

2020-09-23 17:10 UTC, helloTsubasa commented on config/routes.rb
> +  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show]
おっしゃる通りです！ありがとうございます直しました！

2020-09-24 01:10 UTC, sew-sou19 approved these changes
LGTMですー！

2020-09-24 01:13 UTC, merged