掲示板投稿機能
junkratmecha/tenkue-board-r002 pull request #3
Opened 2020-09-18 06:58 UTC by ka-zu-ki

-掲示板を投稿できるようにした（new,create）
-validation（投稿内容必須、１４０字以内）
-エラーメッセージ
-日本語化
-投稿画面でログインん要求

2020-09-19 08:31 UTC, helloTsubasa commented on app/controllers/posts_controller.rb
> +  end
```.build```ではなく```.new``` で良いと思います！

もしcurret_userの情報を紐付けるなら、privateメソッドのpost_paramsで```.merge```すればいけます！

2020-09-19 14:24 UTC, sew-sou19 requested changes
レビュー完了しましたー！
指摘に対して1件ずつリプか反応をお願いします。修正後再度依頼をしてください！

2020-09-19 14:24 UTC, sew-sou19 commented on app/views/posts/new.html.erb
> +      <%= form_with(model: @post, url: posts_path, method: 'post', local: true) do |f| %>
```suggestion
      <%= form_with(model: @post, local: true) do |f| %>
```
form_withは、URIを自動で判定してくれるのでここでの記述は不要ですー！

2020-09-19 14:24 UTC, sew-sou19 commented on config/routes.rb
> -  resources :posts, only: :index
今更で申し訳ないですが、rootパスを設定しましょう！（junkratさんの実装の際に指摘すべきでした🙇‍♂️）

2020-09-19 14:24 UTC, sew-sou19 commented on app/models/post.rb
> +  validates :content, presence: true
このままでも動作は問題ないですが、リファクタ可能です！
```suggestion
  validates :content, {length: { maximum: 140 }, presence: true}
```

2020-09-20 03:55 UTC, ka-zu-ki commented on app/models/post.rb
> +  validates :content, presence: true
ありがとうございます！この書き方はじめて知りました笑

2020-09-20 06:28 UTC, sew-sou19 requested changes
細かいですが1点だけ修正お願いしますー！

2020-09-20 06:28 UTC, sew-sou19 commented on app/models/post.rb
> +  validates :content, length: { maximum: 140 }
`validates :content, {length: { maximum: 140 }, presence: true}`で140文字の制限かけてるので、こっちの記述は消しましょう！

2020-09-20 06:32 UTC, sew-sou19 approved these changes
LGTMですー！

2020-09-20 06:33 UTC, merged