掲示板編集/削除機能
junkratmecha/tenkue-board-r002 pull request #5
Opened 2020-09-20 08:53 UTC by ka-zu-ki

- 投稿内容を変更できる

- 投稿を削除できる

- ログインしていなければ編集、削除、遷移できない

- バリデーション、エラーメッセージ

-

-

2020-09-20 10:21 UTC, sew-sou19 requested changes
レビュー完了しました。
一部確認をお願いしますー！

2020-09-20 10:21 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @post = Post.find(params[:id])
`@post = Post.find(params[:id])`の記述がupdateアクションと重複してるのでここはリファクタリングできます！
privateメソッドで定義してbefore_actionで呼び出してあげると綺麗です

2020-09-20 10:21 UTC, sew-sou19 commented on app/views/posts/edit.html.erb
> +      <%= form_with(model: @post, method: 'put', local: true) do |f| %>
このフォーム部分は、posts/newと共通してるのでリファクタリングできます！
部分テンプレート化して読み込んであげると綺麗です

2020-09-20 10:21 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +  def edit
”投稿者だけが”該当の掲示板の編集ページに遷移できるように条件分岐を設定しましょう！

2020-09-20 12:25 UTC, ka-zu-ki commented on app/controllers/posts_controller.rb
> +  def edit
viewで`<% if user_signed_in? && current_user == post.user %>`としているのですが
controllerでもやる必要があるのでしょうか？

2020-09-21 16:56 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +  def edit
URLベタ打ちで飛べてしまうので、コントローラーで制限するのがベターです！

2020-09-21 17:00 UTC, sew-sou19 requested changes
レビュー完了しました！
あと1点だけリファクタをお願いします🙏

2020-09-22 10:11 UTC, sew-sou19 commented
コンフリクト解消しましょう！

2020-09-22 10:12 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    if current_user.id != @post user.id
ここ見落としてました🙇‍♂️
```suggestion
    if current_user.id != @post.user.id
```
が正しいですね！

2020-09-22 10:22 UTC, sew-sou19 approved these changes
完璧ですー！LGTMです

2020-09-22 10:23 UTC, merged